# Generated by Django 5.2.4 on 2025-07-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('cholesterol', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('max_heart_rate', models.FloatField()),
                ('prediction', models.BooleanField()),
            ],
        ),
    ]
